### ISSUE TITLE
How to set the max expression length?

### ISSUE THREAD

**Issue by lawpdas** [nku-shengzheliu/Pytorch-TransVG#1]

**Comment by nku-shengzheliu** [comment]
You can change the maximum expression length by setting `args.time`, for example, during training use the command:
```
python train.py --time {XX}
```

**Comment by lawpdas** [comment]
"We cut off the language query if its length is longer than 38”. So we directly cut off the language within the dataloader? I think it is unreasonable. Do I misunderstand?

**Comment by nku-shengzheliu** [comment]
I guess maybe most of the expressions are less than 38 words so the author chose to cut them off. 
This may affect performance if the expression is too long. Do you have a better approach to share?

**Comment by lawpdas** [comment]
Sorry, I have no idea about that. I'm a beginner in visual language.
Thanks for your implementation!
