### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by Peteryoung258** [nku-shengzheliu/Pytorch-TransVG#3]

**Comment by Peteryoung258** [comment]
can i have a look at your structure of datasets, i've sufferred it for a whole day.[lol]

**Comment by nku-shengzheliu** [comment]
I use the `--data_root` to set the directory that stores the dataset images.
Here is the structure of data_root:
```
--data_root/
	--coco2014/
		--train2014/
			--XXX.jpg
			--XXX.jpg
			...
		--val2014/
			--XXX.jpg
			--XXX.jpg
			...
	--referit/
		--images/
			--XXX.jpg
			--XXX.jpg
			...
```
The dataset annotation file can be prepared according to the **Installation** subsection of [ReSC](https://github.com/zyang-ur/ReSC).
