### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by erfan-ghadery** [nku-shengzheliu/Pytorch-TransVG#4]
Thanks for your nice implementation. It would be nice if you could provide some information about the training time on Flickr or Referit dataset because I found it very slow. Thanks in advance!

**Comment by nku-shengzheliu** [comment]
Hi erfan-ghadery, I haven't trained on Flickr yet. It takes me about 40 minutes per epoch to train using two 1080ti on the Referit dataset. Hope this is helpful.
