### ISSUE TITLE
About data preparation

### ISSUE THREAD

**Issue by yuanze-lin** [nku-shengzheliu/Pytorch-TransVG#5]
I cannot download split files, the link is "https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2". Can you share this file in TransVG repo ? Thanks a lot !

**Comment by nku-shengzheliu** [comment]
Sorry for the late reply...do you mean this file?[Google drive](https://drive.google.com/file/d/17voXrVtga2yyjeEx78VTMqZhpX0I8yH1/view?usp=sharing)
